export const HINDI_PLAYLISTS = [
  {
    id: "80632334",
    title: "Hum Hindustani",
    subtitle: "63.2K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/HumHindustani_20230802055725.jpg",
    perma_url: "https://www.jiosaavn.com/featured/hum-hindustani/WFpyg06H4I8_",
    more_info: {
      song_count: "39",
      firstname: "JioSaavn",
      follower_count: "63213",
      last_updated: "1705969977",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "946682072",
    title: "Most Searched Songs - Hindi",
    subtitle: "62.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MostSearchedSongsHindi_20231219045222.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/most-searched-songs-hindi/csv-SfcHUmHc1EngHtQQ2g__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "62514",
      last_updated: "1705939775",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "79653434",
    title: "Non-Stop Party Mix",
    subtitle: "224.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/NonStopPartyMix_20231226060733.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/non-stop-party-mix/FPfWwWPUJ5I_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "224727",
      last_updated: "1703531273",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "58057412",
    title: "Let's Play - Arijit Singh - Hindi",
    subtitle: "723.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayArijitSinghHindi_20230825050128.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-arijit-singh-hindi/Iz0pi7nkjUE_",
    more_info: {
      song_count: "51",
      firstname: "JioSaavn",
      follower_count: "723874",
      last_updated: "1705970100",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158207098",
    title: "Romantic Remakes",
    subtitle: "75.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/RomanticRemakes_20230525060604.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/romantic-remakes/ZcJ2DBEDltBFo9wdEAzFBA__",
    more_info: {
      song_count: "36",
      firstname: "JioSaavn",
      follower_count: "75933",
      last_updated: "1705515121",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1079336813",
    title: "Chill Maaro: Lo-Fi Mix",
    subtitle: "3.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/ChillMaaro-LoFiMix_20220908174414.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/chill-maaro-lo-fi-mix/mAA3xzx2Asqm0KYf4sgO,Q__",
    more_info: {
      song_count: "28",
      firstname: "JioSaavn",
      follower_count: "3513",
      last_updated: "1705003795",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "107724265",
    title: "Punjab Se Bollywood",
    subtitle: "338.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/PunjabseBollywood_20221125094913.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/punjab-se-bollywood/obx07Zza,rHuCJW60TJk1Q__",
    more_info: {
      song_count: "23",
      firstname: "JioSaavn",
      follower_count: "338677",
      last_updated: "1703103467",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "618326972",
    title: "Decade Of 2010s: Singers",
    subtitle: "49.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/DecadeofSingers-201019_20230120065159.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/decade-of-2010s-singers/QtQqElZyMoDc1EngHtQQ2g__",
    more_info: {
      song_count: "42",
      firstname: "JioSaavn",
      follower_count: "49307",
      last_updated: "1703103095",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "149267518",
    title: "Indipop Sad Songs",
    subtitle: "27.4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/IndipopSadSongs_20230526175619.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/indipop-sad-songs/QTZoJQAOnmZFo9wdEAzFBA__",
    more_info: {
      song_count: "31",
      firstname: "JioSaavn",
      follower_count: "27396",
      last_updated: "1705969786",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "39416670",
    title: "Let's Play - Kumar Sanu - Hindi",
    subtitle: "348.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayKumarSanuHindi_20230809073818.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-kumar-sanu-hindi/QeBmhG7Y1uE_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "348182",
      last_updated: "1703102607",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "804316688",
    title: "Best Of EDM - Hindi",
    subtitle: "20.3K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/BestOfEDMHindi_20231026182059.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-edm-hindi/OYy8Eam-WpZFo9wdEAzFBA__",
    more_info: {
      song_count: "27",
      firstname: "JioSaavn",
      follower_count: "20288",
      last_updated: "1699308016",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "757656308",
    title: "2000s Duets - Hindi",
    subtitle: "90.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/2000sDuets_20211203161917.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/2000s-duets-hindi/NaV3HkhAB5FFo9wdEAzFBA__",
    more_info: {
      song_count: "22",
      firstname: "JioSaavn",
      follower_count: "90314",
      last_updated: "1703103229",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "83421839",
    title: "Ishqiyaan",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Ishqiyaan_20240121180831.jpg",
    perma_url: "https://www.jiosaavn.com/featured/ishqiyaan/dyqSeSlJrvI_",
    more_info: {
      song_count: "27",
      firstname: "JioSaavn",
      follower_count: "610472",
      last_updated: "1706059805",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "107605145",
    title: "It's Indie - Hindi",
    subtitle: "6.5K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/It_sIndieHindi_20240103162542.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/its-indie-hindi/jnjK2XTv9-3uCJW60TJk1Q__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "6482",
      last_updated: "1705969864",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "6689255",
    title: "Taaza Tunes",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/TaazaTunes_20240119105315.jpg",
    perma_url: "https://www.jiosaavn.com/featured/taaza-tunes/Me5RridRfDk_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "597429",
      last_updated: "1706141932",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "835868172",
    title: "Decade Of Heroes - 2000s",
    subtitle: "5.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/DecadeOfHeroes2000s_20210824152944.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/decade-of-heroes-2000s/GCYuCLBbqmfc1EngHtQQ2g__",
    more_info: {
      song_count: "29",
      firstname: "JioSaavn",
      follower_count: "5842",
      last_updated: "1704772490",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "5148894",
    title: "Nach Le",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/NachLe_20231212110845.jpg",
    perma_url: "https://www.jiosaavn.com/featured/nach-le/UQjTO6rFZfc_",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "541074",
      last_updated: "1706025170",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "903166403",
    title: "Best Of Romance - Hindi",
    subtitle: "103.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOfRomanceHindi_20231117032844.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-romance-hindi/SBKnUgjNeMIwkg5tVhI3fw__",
    more_info: {
      song_count: "53",
      firstname: "JioSaavn",
      follower_count: "103450",
      last_updated: "1703102601",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "156473621",
    title: "Pop Mein Top",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/PopMeinTop_20240125110622.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/pop-mein-top/pDQtHvJRh4IGSw2I1RxdhQ__",
    more_info: {
      song_count: "26",
      firstname: "JioSaavn",
      follower_count: "263064",
      last_updated: "1706141207",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1139074020",
    title: "Most Streamed Love Songs: Hindi",
    subtitle: "36.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MostStreamedLoveSongs-Hindi_20231225150048.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/most-streamed-love-songs-hindi/RQKZhDpGh8uAIonqf0gmcg__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "36631",
      last_updated: "1705939190",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "932189657",
    title: "Best Of Dance - Hindi",
    subtitle: "61.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOfDanceHindi_20231026182028.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-dance-hindi/qVvfieICUY5ieSJqt9HmOQ__",
    more_info: {
      song_count: "51",
      firstname: "JioSaavn",
      follower_count: "61745",
      last_updated: "1705517232",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158223987",
    title: "Chill Maaro",
    subtitle: "40.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/ChillMaaro_20231117040907.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/chill-maaro/CZTTBas4j8RieSJqt9HmOQ__",
    more_info: {
      song_count: "22",
      firstname: "JioSaavn",
      follower_count: "40859",
      last_updated: "1703104971",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "330056058",
    title: "Best Of Rock - Hindi",
    subtitle: "25.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOfRockHindi_20231005121959.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-rock-hindi/DGl4UBWnRqlFo9wdEAzFBA__",
    more_info: {
      song_count: "26",
      firstname: "JioSaavn",
      follower_count: "25234",
      last_updated: "1703105948",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "810634923",
    title: "Best Of Sad Songs: 2000s",
    subtitle: "47.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOfSadSongs-2000s_20230831102015.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-sad-songs-2000s/KQaWtlmKQuQwkg5tVhI3fw__",
    more_info: {
      song_count: "21",
      firstname: "JioSaavn",
      follower_count: "47227",
      last_updated: "1703103643",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "159241733",
    title: "Wow Winters - Mausam Mastana",
    subtitle: "21.2K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/MausamMastana_20231205052543.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/wow-winters-mausam-mastana/d9QpQIMxKE8wkg5tVhI3fw__",
    more_info: {
      song_count: "21",
      firstname: "JioSaavn",
      follower_count: "21192",
      last_updated: "1704149285",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "101704478",
    title: "Jhakaas Remakes",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/JhakaasRemakes_20230404064405.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/jhakaas-remakes/7e2LtwVBX6JFo9wdEAzFBA__",
    more_info: {
      song_count: "42",
      firstname: "JioSaavn",
      follower_count: "356612",
      last_updated: "1706152277",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158222753",
    title: "Lyrically Mast",
    subtitle: "12.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/LyricallyMast_20210901161257.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lyrically-mast/BWNIAJIwMPkwkg5tVhI3fw__",
    more_info: {
      song_count: "23",
      firstname: "JioSaavn",
      follower_count: "12331",
      last_updated: "1701391782",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158221880",
    title: "Best Of Retro",
    subtitle: "31.4K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/BestOfRetro_20230831100603.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-retro/IFTYFbu2anRuOxiEGmm6lQ__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "31386",
      last_updated: "1703114585",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "10301457",
    title: "Arijit Singh - Love Songs - Hindi ",
    subtitle: "182.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/ArijitKiAashiqui_20210202085733.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/arijit-singh-love-songs-hindi-/vAGc-2PQBuk_",
    more_info: {
      song_count: "31",
      firstname: "JioSaavn",
      follower_count: "182297",
      last_updated: "1704836732",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "72903410",
    title: "Sirf Unplugged",
    subtitle: "92.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/SirfUnplugged_20230531161214.jpg",
    perma_url: "https://www.jiosaavn.com/featured/sirf-unplugged/QkY0PeqdTW4_",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "92145",
      last_updated: "1703115555",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1164340768",
    title: "Best Of 2010s",
    subtitle: "27.8K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/BestOf2010s_20230831102105.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-2010s/gn19HTwL-lfgEhiRleA1SQ__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "27799",
      last_updated: "1703113351",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1020129788",
    title: "Men In Indipop: New Hits",
    subtitle: "Just Updated",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MenInIndipop-NewHits_20231013190219.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/men-in-indipop-new-hits/Bxu4BRUH9dXDN85e-DKVsA__",
    more_info: {
      song_count: "26",
      firstname: "JioSaavn",
      follower_count: "19248",
      last_updated: "1706035813",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1023629070",
    title: "Best Of Romance: Retro - Hindi",
    subtitle: "33.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOfRomance-RetroHindi_20230831100836.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-romance-retro-hindi/O58xFfZTpydwtkLw7-JlUw__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "33856",
      last_updated: "1703114696",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158229653",
    title: "2000s Dance Dhamaaka",
    subtitle: "30.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/2000sDanceDhamaaka_20230831102010.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/2000s-dance-dhamaaka/9zxDaumQx1gwkg5tVhI3fw__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "30597",
      last_updated: "1703115761",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "153572365",
    title: "Josh Hi Josh",
    subtitle: "85.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/JoshHiJosh_20230701032021.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/josh-hi-josh/DByzia6eJfXuCJW60TJk1Q__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "85902",
      last_updated: "1704158858",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "156654587",
    title: "Let's Play - Jubin Nautiyal - Hindi",
    subtitle: "90.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayJubinNautiyalHindi_20230809073812.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-jubin-nautiyal-hindi/cyd1elB4lx5ieSJqt9HmOQ__",
    more_info: {
      song_count: "33",
      firstname: "JioSaavn",
      follower_count: "90336",
      last_updated: "1703114685",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1080335349",
    title: "Hindi Hit Songs",
    subtitle: "15.5K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/HindiHitSongs_20231227172200.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/hindi-hit-songs/ZodsPn39CSjwxP8tCU-flw__",
    more_info: {
      song_count: "26",
      firstname: "JioSaavn",
      follower_count: "15510",
      last_updated: "1703668939",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "155321547",
    title: "2000s Romance - Hindi",
    subtitle: "51.1K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/2000sRomanceHindi_20230523050812.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/2000s-romance-hindi/C-YFu69qRHVieSJqt9HmOQ__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "51069",
      last_updated: "1703116175",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "87336382",
    title: "Best Of Indipop - 90s",
    subtitle: "8.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/IndipopFavorites90sSpecial_20231120095809.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-indipop-90s/Mxb0lhMGe5Q_",
    more_info: {
      song_count: "24",
      firstname: "JioSaavn",
      follower_count: "8894",
      last_updated: "1704783936",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "159285384",
    title: "Labon Ka Karobaar",
    subtitle: "78.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/LabonKaKarobaar_20231227111200.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/labon-ka-karobaar/n-1VUvQ1UYDufxkxMEIbIw__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "78535",
      last_updated: "1703648090",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "154632129",
    title: "Only Khushiyaan",
    subtitle: "33.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/OnlyKhushiyaan_20231117032829.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/only-khushiyaan/JIFP3OT7,SmO0eMLZZxqsA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "33908",
      last_updated: "1703116358",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "155321561",
    title: "Best Of 2000s - Hindi",
    subtitle: "67.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOf2000sHindi_20230901051004.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-2000s-hindi/w,zEBfumNkQGSw2I1RxdhQ__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "67794",
      last_updated: "1703114086",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "618308794",
    title: "Decade Of 2010s: Dance Dhamaaka - Hindi",
    subtitle: "40.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/DecadeOf2010s-DanceHindi_20230831102201.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/decade-of-2010s-dance-dhamaaka-hindi/cEnot2wLglbufxkxMEIbIw__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "40617",
      last_updated: "1703114106",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "940775963",
    title: "Best Of Indipop - Hindi",
    subtitle: "15.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestOfIndipopHindi_20220817093953.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-indipop-hindi/xHa-oM3ldXAwkg5tVhI3fw__",
    more_info: {
      song_count: "31",
      firstname: "JioSaavn",
      follower_count: "15642",
      last_updated: "1703116570",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "4340227",
    title: "Let's Play - Ranbir Kapoor",
    subtitle: "14.1K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayRanbirKapoor_20230809074210.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-ranbir-kapoor/TmVxhTfZgT0_",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "14088",
      last_updated: "1703117067",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1077765822",
    title: "Best Of Electro - Hindi",
    subtitle: "7.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/DesiElectro_20230926061712.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-electro-hindi/stznSe1BLQGTQcXlxedPDQ__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "7912",
      last_updated: "1704788701",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
];

export const ENGLISH_PLAYLISTS = [
  {
    id: "945969391",
    title: "Most Searched Songs - English",
    subtitle: "19.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MostSearchedSongsEnglish_20240108090530.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/most-searched-songs-english/xUOBWZUG6AgGSw2I1RxdhQ__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "19867",
      last_updated: "1705967154",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "103330400",
    title: "Fresh Rock Hits - English",
    subtitle: "9.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/FreshRockHitsEnglish_20240119120209.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/fresh-rock-hits-english/LlG94Or10VVuOxiEGmm6lQ__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "9492",
      last_updated: "1705638940",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158049570",
    title: "Chill Beats",
    subtitle: "6.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/ChillBeats_20240119123946.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/chill-beats/suCVEatbqVBuOxiEGmm6lQ__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "6140",
      last_updated: "1705639564",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "157182542",
    title: "Let's Play - Halsey",
    subtitle: "1.4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayHalsey_20240117050223.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-halsey/e7,gtJ5jKk7c1EngHtQQ2g__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "1443",
      last_updated: "1705439051",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "146434735",
    title: "Fresh Latin Hits",
    subtitle: "17.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FreshLatinHits_20240119115837.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/fresh-latin-hits/iZf3wDHw2nTuCJW60TJk1Q__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "17880",
      last_updated: "1705636909",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "87510850",
    title: "Most Streamed Love Songs - English",
    subtitle: "26.1K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MostStreamedLoveSongsEnglish_20240123073547.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/most-streamed-love-songs-english/wHN0Jq26XqA_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "26127",
      last_updated: "1705966930",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "82914609",
    title: "It's Indie - English",
    subtitle: "3.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/It_sIndieEnglish_20240119124927.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/its-indie-english/AMoxtXyKHoU_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "3895",
      last_updated: "1705639962",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "731431216",
    title: "Let's Play - Jonas Brothers",
    subtitle: "389 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayJonasBrothers_20240117045946.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-jonas-brothers/qGUtX33J4OLfemJ68FuXsA__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "389",
      last_updated: "1705438890",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "902306817",
    title: "VIRALnation",
    subtitle: "35.2K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/VIRALnation_20240112123700.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/viralnation/tfVkYjaAbZJieSJqt9HmOQ__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "35245",
      last_updated: "1705441978",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158225563",
    title: "Hollywood Movie Hits",
    subtitle: "3.4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/HollywoodMovieHits_20240117045917.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/hollywood-movie-hits/JILX9arsAk8wkg5tVhI3fw__",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "3358",
      last_updated: "1705971708",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "88850418",
    title: "House Party - English",
    subtitle: "6.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/HousePartyEnglish_20231117131455.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/house-party-english/IPm9oKHppSA_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "6186",
      last_updated: "1705971866",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "88005154",
    title: "Let's Play - OneRepublic",
    subtitle: "554 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayOneRepublic_20240117050152.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-onerepublic/YqAHVoCbpFI_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "554",
      last_updated: "1705438935",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "86183802",
    title: "Rap Cypher - English",
    subtitle: "Just Updated",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/RapCypherEnglish_20240112115000.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/rap-cypher-english/nc,LQ5hFF2I_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "74096",
      last_updated: "1706058131",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "159451264",
    title: "TV Tunes",
    subtitle: "1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/tvtunes_20240117045142.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/tv-tunes/Ycxx-Ge0j0jufxkxMEIbIw__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "1027",
      last_updated: "1705438368",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "81169234",
    title: "Now Playing Pop",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/NowPlayingPop_20231208135830.jpg",
    perma_url: "https://www.jiosaavn.com/featured/now-playing-pop/IQO11xk800E_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "180172",
      last_updated: "1706057781",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "81399744",
    title: "Heartbeats",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Heartbeats_20240119114354.jpg",
    perma_url: "https://www.jiosaavn.com/featured/heartbeats/8j,bJexTYcE_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "109072",
      last_updated: "1706057100",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "87109788",
    title: "Hip Hop Workout",
    subtitle: "12K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/HipHopWorkout_20230906195033.jpg",
    perma_url: "https://www.jiosaavn.com/featured/hip-hop-workout/VV85AiO5f7g_",
    more_info: {
      song_count: "45",
      firstname: "JioSaavn",
      follower_count: "12038",
      last_updated: "1705364885",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "85481065",
    title: "Fresh Tunes",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FreshTunes_20240119102823.jpg",
    perma_url: "https://www.jiosaavn.com/featured/fresh-tunes/Ns2UZo9qDvI_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "222688",
      last_updated: "1706153848",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "159144718",
    title: "Feel Good Pop",
    subtitle: "14.4K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FeelGoodPop_20231117131440.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/feel-good-pop/Er9SBlcxDtZFo9wdEAzFBA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "14390",
      last_updated: "1705439874",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "87000197",
    title: "Essential Soft Pop",
    subtitle: "13.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/EssentialSoftPop_20240105123808.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/essential-soft-pop/vw3rxyOhUs8_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "13479",
      last_updated: "1705367675",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "283365996",
    title: "EDM Uplift",
    subtitle: "9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/EDMUplift_20240104022119.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/edm-uplift/NIgocfKoeoPfemJ68FuXsA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "9006",
      last_updated: "1705451395",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "175504939",
    title: "New Year, New You",
    subtitle: "3.3K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/NewYear-NewYou_20231230093557.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/new-year-new-you/2pOsOvc4bXaO0eMLZZxqsA__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "3256",
      last_updated: "1704683536",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1210788156",
    title: "Let's Play - Adele",
    subtitle: "JioSaavn",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Let_sPlayAdele_20240103112659.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-adele/pVh19D03XxOvz,QNANKgeg__",
    more_info: {
      song_count: "20",
      firstname: "JioSaavn",
      follower_count: "38",
      last_updated: "1704305285",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "84902960",
    title: "Treadmill Pop",
    subtitle: "12K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/TreadmillPop_20231208140210.jpg",
    perma_url: "https://www.jiosaavn.com/featured/treadmill-pop/SF9VDfc5vr4_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "11998",
      last_updated: "1704683817",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "442379728",
    title: "The Sound Of Afrobeat",
    subtitle: "2.4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/TheSoundOfAfrobeat_20231201123525.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/the-sound-of-afrobeat/QyqPhVd4ZFhFo9wdEAzFBA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "2421",
      last_updated: "1704248984",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158767012",
    title: "Fresh Metal Hits",
    subtitle: "4.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FreshMetalHits_20231201121034.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/fresh-metal-hits/Nf3OsreD7kTc1EngHtQQ2g__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "4124",
      last_updated: "1705638845",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "49927455",
    title: "And The Nominees Are",
    subtitle: "5.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/AndTheNomineesAre_20231111092527.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/and-the-nominees-are/3efFnRKzFzk_",
    more_info: {
      song_count: "85",
      firstname: "JioSaavn",
      follower_count: "5824",
      last_updated: "1699731057",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "81852466",
    title: "Fresh RnB",
    subtitle: "14.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FreshRnB_20231110135457.jpg",
    perma_url: "https://www.jiosaavn.com/featured/fresh-rnb/kwJkRwJz89k_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "14061",
      last_updated: "1705637999",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "61470767",
    title: "Fresh Country Hits",
    subtitle: "4.1K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/FreshCountryHits_20231110142737.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/fresh-country-hits/WnfLufQpDCg_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "4123",
      last_updated: "1705638159",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "208571376",
    title: "Hip Hop Dance Hits",
    subtitle: "10.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/HipHopDanceHits_20231027032014.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/hip-hop-dance-hits/oLEjsCVbtfLfemJ68FuXsA__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "10312",
      last_updated: "1703026683",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "110268793",
    title: "Let's Play - Drake",
    subtitle: "2.4K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Let_sPlayDrake_20231023173557.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-drake/MBMuHZ,FJygwkg5tVhI3fw__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "2397",
      last_updated: "1700200013",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "100252778",
    title: "Chill Hip Hop",
    subtitle: "3.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/ChillHipHop_20230816110536.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/chill-hip-hop/kwiWzGxnBXNFo9wdEAzFBA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "3127",
      last_updated: "1705452184",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "84801008",
    title: "Let's Play - The Beatles",
    subtitle: "2.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayTheBeatles_20231103055738.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-the-beatles/lMSdD9QqsaE_",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "2476",
      last_updated: "1698965958",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "89593838",
    title: "Fresh Dance Hits",
    subtitle: "14.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FreshDanceHits_20240119103553.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/fresh-dance-hits/rEDxb7swgvE_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "14108",
      last_updated: "1705636818",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "84965242",
    title: "Essential Soft Rock",
    subtitle: "5.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/EssentialSoftRock_20230606105444.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/essential-soft-rock/h1UJgj82Tz4_",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "5630",
      last_updated: "1705451365",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "90522027",
    title: "Let's Play - Alan Walker",
    subtitle: "41.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayAlanWalker_20230809091030.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-alan-walker/277qKJrlBTo_",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "41791",
      last_updated: "1704427359",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "163362514",
    title: "Best of Classic Rock",
    subtitle: "11.4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/AbsoluteClassicRock_20230818133003.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-classic-rock/bfVvvAV,lf3ufxkxMEIbIw__",
    more_info: {
      song_count: "100",
      firstname: "JioSaavn",
      follower_count: "11392",
      last_updated: "1705360619",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "72148235",
    title: "Let's Play - Freddie Mercury",
    subtitle: "3.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayFreddieMercury_20230904182647.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-freddie-mercury/4nxhv,I7tkw_",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "3701",
      last_updated: "1694855928",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "154038885",
    title: "MARVELous Heroes",
    subtitle: "12.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MARVELousHeroes_20230602141625.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/marvelous-heroes/D5GDD6tcluXuCJW60TJk1Q__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "12238",
      last_updated: "1691380415",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "66391811",
    title: "Let's Play - Selena Gomez",
    subtitle: "13K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlaySelenaGomez_20231018052134.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-selena-gomez/XvrpnngQRBE_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "12979",
      last_updated: "1697581307",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "280083933",
    title: "Let's Play - Taylor Swift",
    subtitle: "5.3K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayTaylorSwift_20231018052211.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-taylor-swift/EsbCWUC3q5Ewkg5tVhI3fw__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "5279",
      last_updated: "1705450549",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "302927027",
    title: "Moondance",
    subtitle: "2.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Moondance_20230824055722.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/moondance/ttyS2TparGBieSJqt9HmOQ__",
    more_info: {
      song_count: "22",
      firstname: "JioSaavn",
      follower_count: "2091",
      last_updated: "1692831462",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "79579889",
    title: "Let's Play - Sia",
    subtitle: "10.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Let_sPlaySia_20231020140212.jpg",
    perma_url: "https://www.jiosaavn.com/featured/lets-play-sia/ZFD-DFK14YY_",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "10859",
      last_updated: "1702862872",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "107320028",
    title: "Fresh K-Pop Hits",
    subtitle: "Just Updated",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/FreshKPopHits_20240124083839.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/fresh-k-pop-hits/qmcsGAI9mRFFo9wdEAzFBA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "34901",
      last_updated: "1706056907",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "410795064",
    title: "K-Pop Dance Hits",
    subtitle: "4.8K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/KPopDanceHits_20231025095648.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/k-pop-dance-hits/nu8lkO4o-inufxkxMEIbIw__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "4753",
      last_updated: "1705361962",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "151505252",
    title: "Let's Play - Backstreet Boys",
    subtitle: "1.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/LargerThanLifeBackstreetBoys_20211110040933.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-backstreet-boys/ACUx,3lyMEfc1EngHtQQ2g__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "1775",
      last_updated: "1690254728",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "109434663",
    title: "Kids Movie Hits",
    subtitle: "3.4K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/KidsMovieHits_20231212095402.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/kids-movie-hits/B9ntHBM3OGwwkg5tVhI3fw__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "3377",
      last_updated: "1702346315",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
];

export const PUNJABI_PLAYLISTS = [
  {
    id: "273687785",
    title: "Let's Play - Jass Manak - Punjabi",
    subtitle: "Just Updated",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayJassManakPunjabi_20240125083416.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-jass-manak-punjabi/ucN8,mPZSHvuCJW60TJk1Q__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "33837",
      last_updated: "1706142870",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "946945296",
    title: "Most Searched Songs - Punjabi",
    subtitle: "5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MostSearchedSongsPunjabi_20231218100921.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/most-searched-songs-punjabi/bZov-8koUTzfemJ68FuXsA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "4972",
      last_updated: "1705966925",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "976846225",
    title: "Wow Winters - Siyaal Te Pyaar - Punjabi",
    subtitle: "396 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/WowWintersSiyaalTePyaarPunjabi_20231205051647.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/wow-winters-siyaal-te-pyaar-punjabi/ITheaNwG7aLuCJW60TJk1Q__",
    more_info: {
      song_count: "21",
      firstname: "JioSaavn",
      follower_count: "396",
      last_updated: "1702430193",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "899365493",
    title: "Let's Play - Shehnaaz Gill - Punjabi",
    subtitle: "662 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayShehnaazGillPunjabi_20231207163216.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-shehnaaz-gill-punjabi/yu1cCO8dpPEwkg5tVhI3fw__",
    more_info: {
      song_count: "21",
      firstname: "JioSaavn",
      follower_count: "662",
      last_updated: "1701937950",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "810005957",
    title: "Let's Play - Afsana Khan - Punjabi",
    subtitle: "1.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayAfsanaKhanPunjabi_20231212060121.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-afsana-khan-punjabi/fMSjAariIDFieSJqt9HmOQ__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "1205",
      last_updated: "1705969669",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "905068346",
    title: "Brown Munde",
    subtitle: "4.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/BrownMundePunjabi_20220212161315.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/brown-munde/3-QhuhOqQfnfemJ68FuXsA__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "4688",
      last_updated: "1702349604",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "979042969",
    title: "Let's Play - Harnoor - Punjabi",
    subtitle: "1.4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayHarnoorPunjabi_20231205070923.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-harnoor-punjabi/3dUyMPoUCbKO0eMLZZxqsA__",
    more_info: {
      song_count: "23",
      firstname: "JioSaavn",
      follower_count: "1410",
      last_updated: "1701731376",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "935734052",
    title: "It's Indie - Punjabi",
    subtitle: "105 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/It_sIndiePunjabi_20231031083825.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/its-indie-punjabi/9f-F4X-0-7jc1EngHtQQ2g__",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "105",
      last_updated: "1705024118",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "4511435",
    title: "Let's Play - Babbu Maan - Punjabi",
    subtitle: "9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayBabbuMaanPunjabi_20231207162744.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-babbu-maan-punjabi/uEUnVuux4vo_",
    more_info: {
      song_count: "38",
      firstname: "JioSaavn",
      follower_count: "8959",
      last_updated: "1704235537",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158226121",
    title: "Best of Dance - Punjabi",
    subtitle: "325 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/PunjabiDanceHits2017_20231103095753.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-dance-punjabi/XO3d1ApixxgGSw2I1RxdhQ__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "325",
      last_updated: "1704235595",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "765363046",
    title: "Chill Mode - Punjabi",
    subtitle: "6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/ChillModePunjabi_20231120070134.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/chill-mode-punjabi/qhVxya5MF,-femJ68FuXsA__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "5984",
      last_updated: "1702343583",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "247384393",
    title: "Let's Play - Karan Aujla - Punjabi",
    subtitle: "30.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayKaranAujlaPunjabi_20231207083151.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-karan-aujla-punjabi/kif3TQE58RIwkg5tVhI3fw__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "30848",
      last_updated: "1704235062",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1139373783",
    title: "Most Streamed Love Songs - Punjabi",
    subtitle: "2.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/MostStreamedLoveSongsPunjabi_20240115175125.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/most-streamed-love-songs-punjabi/A0,SyjfVbP4C0-RsHAbZ7g__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "2771",
      last_updated: "1705966736",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "957490979",
    title: "Let's Play - Kaka - Punjabi",
    subtitle: "9.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayKakaPunjabi_20231207083053.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-kaka-punjabi/AbAp-sTfCieO0eMLZZxqsA__",
    more_info: {
      song_count: "30",
      firstname: "JioSaavn",
      follower_count: "9944",
      last_updated: "1705541652",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "159470021",
    title: "Swag Originals Da",
    subtitle: "4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/SwagOriginalsDa_20230419080226.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/swag-originals-da/wGETyb6euaUGSw2I1RxdhQ__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "4037",
      last_updated: "1703025879",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "803341237",
    title: "Let's Play - Nimrat Khaira - Punjabi",
    subtitle: "4.1K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayNimratKhairaPunjabi_20231207083300.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-nimrat-khaira-punjabi/t,g,QwMdjklieSJqt9HmOQ__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "4135",
      last_updated: "1704791095",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158225486",
    title: "Best of Romance - Punjabi",
    subtitle: "21.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestofRomancePunjabi_20231120065919.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-romance-punjabi/s3X0s4hSgi-femJ68FuXsA__",
    more_info: {
      song_count: "40",
      firstname: "JioSaavn",
      follower_count: "21589",
      last_updated: "1704234637",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1066266159",
    title: "Dance Hits 2022 - Punjabi",
    subtitle: "4.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/DanceHits2022Punjabi_20221207144906.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/dance-hits-2022-punjabi/1ErPVHjUdDSQBCMgztuf8A__",
    more_info: {
      song_count: "20",
      firstname: "JioSaavn",
      follower_count: "4858",
      last_updated: "1700448422",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "3918485",
    title: "Mutiyaar",
    subtitle: "1.8K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Mutiyaar_20231110090340.jpg",
    perma_url: "https://www.jiosaavn.com/featured/mutiyaar/fI-LuxGSqfs_",
    more_info: {
      song_count: "44",
      firstname: "JioSaavn",
      follower_count: "1810",
      last_updated: "1704926378",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "30793386",
    title: "Let's Play - Diljit Dosanjh - Punjabi",
    subtitle: "42.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayDiljitDosanjhPunjabi_20230911070448.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-diljit-dosanjh-punjabi/0kQshFJLbtQ_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "42526",
      last_updated: "1704249289",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "799959094",
    title: "Best of Sad Romantic - Punjabi",
    subtitle: "13K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/SadSongsPunjabi_20221209123356.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-sad-romantic-punjabi/ql-Fy0XF8STufxkxMEIbIw__",
    more_info: {
      song_count: "36",
      firstname: "JioSaavn",
      follower_count: "13002",
      last_updated: "1704234704",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "770450149",
    title: "Let's Play - Baani Sandhu - Punjabi",
    subtitle: "1.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayBaaniSandhuPunjabi_20231212060010.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-baani-sandhu-punjabi/V59ThVwAhGSO0eMLZZxqsA__",
    more_info: {
      song_count: "33",
      firstname: "JioSaavn",
      follower_count: "1913",
      last_updated: "1705629163",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "2677778",
    title: "Gabroo",
    subtitle: "6.1K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/Gabroo_20231101151902.jpg",
    perma_url: "https://www.jiosaavn.com/featured/gabroo/uas2bXeN-kI_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "6128",
      last_updated: "1705020092",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1070105513",
    title: "Desi Pop - Punjabi",
    subtitle: "226 Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/DesiPopPunjabi_20231216101745.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/desi-pop-punjabi/HAKgJ0z2--ym0KYf4sgO,Q__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "226",
      last_updated: "1705627393",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "71158310",
    title: "Let's Play - Guru Randhawa - Punjabi",
    subtitle: "18.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayGuruRandhawaPunjabi_20231205070837.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-guru-randhawa-punjabi/94YhtIvnV08_",
    more_info: {
      song_count: "37",
      firstname: "JioSaavn",
      follower_count: "18667",
      last_updated: "1702343043",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "910741705",
    title: "Romantic Duets - Punjabi",
    subtitle: "Just Updated",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/RomanticDuetsPunjabi_20231219055248.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/romantic-duets-punjabi/T0SjV7ntUk3uCJW60TJk1Q__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "1949",
      last_updated: "1706069324",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1053900960",
    title: "Ghaint Geet",
    subtitle: "1.3K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/GhaintGeet_20230908042931.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/ghaint-geet/rvYK,tIzC6B62UBQeMeB4Q__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "1326",
      last_updated: "1705627633",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "79976479",
    title: "House Party Hits",
    subtitle: "3.2K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/HousePartyHits_Punjabi__20231221052214.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/house-party-hits/wgunJPNO7BQ_",
    more_info: {
      song_count: "33",
      firstname: "JioSaavn",
      follower_count: "3181",
      last_updated: "1705627541",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "834198817",
    title: "Let's Play - Shipra Goyal - Punjabi",
    subtitle: "567 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayShipraGoyalPunjabi_20231207083615.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-shipra-goyal-punjabi/w2MnXsOg251ieSJqt9HmOQ__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "567",
      last_updated: "1702953517",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "950071351",
    title: "Let's Play - AP Dhillon - Punjabi",
    subtitle: "13K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayAPDhillonPunjabi_20231205071159.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-ap-dhillon-punjabi/llCBu43mGUEGSw2I1RxdhQ__",
    more_info: {
      song_count: "31",
      firstname: "JioSaavn",
      follower_count: "13025",
      last_updated: "1704235308",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "158223958",
    title: "Best of Pop - Punjabi",
    subtitle: "157 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestofPopPunjabi_20231106121741.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-pop-punjabi/P-2uHwYEGWlFo9wdEAzFBA__",
    more_info: {
      song_count: "28",
      firstname: "JioSaavn",
      follower_count: "157",
      last_updated: "1699244274",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "577505197",
    title: "Let's Play - Gurlej Akhtar - Punjabi",
    subtitle: "4K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayGurlejAkhtarPunjabi_20231207162806.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-gurlej-akhtar-punjabi/Hy6OxAvqQ5BieSJqt9HmOQ__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "4001",
      last_updated: "1702345131",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "929472140",
    title: "Pind Di Sair",
    subtitle: "164 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/PindDiSair_20210511055002.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/pind-di-sair/OTvltwh1bXduOxiEGmm6lQ__",
    more_info: {
      song_count: "25",
      firstname: "JioSaavn",
      follower_count: "164",
      last_updated: "1703029106",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "154589446",
    title: "Let's Play - Sidhu Moose Wala - Punjabi",
    subtitle: "142.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlaySidhuMooseWalaPunjabi_20231205071122.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-sidhu-moose-wala-punjabi/qkut1WxZp,rfemJ68FuXsA__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "142507",
      last_updated: "1701731495",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "3339437",
    title: "Punjabi Duets",
    subtitle: "43.9K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/PunjabiDuets_20231205101927.jpg",
    perma_url: "https://www.jiosaavn.com/featured/punjabi-duets/BRQ1j4fezTQ_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "43943",
      last_updated: "1705021010",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "953712025",
    title: "Siyaape Pyaar De",
    subtitle: "157 Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/SiyaapePyaarDe_20220518171230.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/siyaape-pyaar-de/2TDMMqzwVV7uCJW60TJk1Q__",
    more_info: {
      song_count: "49",
      firstname: "JioSaavn",
      follower_count: "157",
      last_updated: "1702347166",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1019568203",
    title: "Teri Meri Jodi",
    subtitle: "2.6K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/TeriMeriJodi_20220105200218.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/teri-meri-jodi/-c35a5OA0Rg14faDlWgB3A__",
    more_info: {
      song_count: "35",
      firstname: "JioSaavn",
      follower_count: "2639",
      last_updated: "1704790836",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "782468901",
    title: "Let's Play - Jasmine Sandlas - Punjabi",
    subtitle: "1.7K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayJasmineSandlasPunjabi_20230911070307.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-jasmine-sandlas-punjabi/3i48gvgMeXUGSw2I1RxdhQ__",
    more_info: {
      song_count: "34",
      firstname: "JioSaavn",
      follower_count: "1696",
      last_updated: "1698236327",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1054571528",
    title: "2000s Dance Hits - Punjabi",
    subtitle: "261 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/2000sDanceHitsPunjabi_20230831171128.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/2000s-dance-hits-punjabi/es4,7veKVhcaf0YbnbpnQQ__",
    more_info: {
      song_count: "20",
      firstname: "JioSaavn",
      follower_count: "261",
      last_updated: "1693476700",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "100738310",
    title: "Best of Hip Hop - Punjabi",
    subtitle: "15.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/BestofHipHopPunjabi_20230921072536.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/best-of-hip-hop-punjabi/RyrPgTZDukhuOxiEGmm6lQ__",
    more_info: {
      song_count: "24",
      firstname: "JioSaavn",
      follower_count: "15755",
      last_updated: "1704234790",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "856364905",
    title: "Saheli Naal Hangout",
    subtitle: "8.8K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/SaheliNaalHangout_20230301040754.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/saheli-naal-hangout/YcJ1koCjBhTuCJW60TJk1Q__",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "8847",
      last_updated: "1705627101",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "4215171",
    title: "Let's Play - Harrdy Sandhu - Punjabi",
    subtitle: "16.5K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayHarrdySandhuPunjabi_20231205071023.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-harrdy-sandhu-punjabi/oW5GH5vXVtM_",
    more_info: {
      song_count: "28",
      firstname: "JioSaavn",
      follower_count: "16540",
      last_updated: "1701731437",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1053906595",
    title: "Dance Duets - Punjabi",
    subtitle: "256 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/DanceDuetsPunjabi_20230818054826.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/dance-duets-punjabi/MNTMtguCvtQzKBnAJhUU2A__",
    more_info: {
      song_count: "38",
      firstname: "JioSaavn",
      follower_count: "256",
      last_updated: "1704785667",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "935494297",
    title: "Sounds of Music - Dhol - Punjabi",
    subtitle: "736 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/logo/SoundsofMusicDholPunjabi_20210603153915.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/sounds-of-music-dhol-punjabi/66ZsReoFYRZieSJqt9HmOQ__",
    more_info: {
      song_count: "23",
      firstname: "JioSaavn",
      follower_count: "736",
      last_updated: "1687081469",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "1163839071",
    title: "Punjabi Lo-Fi Songs",
    subtitle: "462 Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/PunjabiLoFiSongs_20230509093724.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/punjabi-lo-fi-songs/betTtWn69oq8m7pOZz2ziw__",
    more_info: {
      song_count: "34",
      firstname: "JioSaavn",
      follower_count: "462",
      last_updated: "1704852375",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "4876538",
    title: "Punjabi Workout",
    subtitle: "18.8K Followers",
    type: "playlist",
    image: "https://c.saavncdn.com/editorial/PunjabiWorkout_20230712220135.jpg",
    perma_url: "https://www.jiosaavn.com/featured/punjabi-workout/1lv8piStXj4_",
    more_info: {
      song_count: "50",
      firstname: "JioSaavn",
      follower_count: "18773",
      last_updated: "1703021071",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
  {
    id: "904490695",
    title: "Let's Play - Shivjot - Punjabi",
    subtitle: "1.9K Followers",
    type: "playlist",
    image:
      "https://c.saavncdn.com/editorial/Let_sPlayShivjotPunjabi_20231207083523.jpg",
    perma_url:
      "https://www.jiosaavn.com/featured/lets-play-shivjot-punjabi/hTj7Yyc6x9XuCJW60TJk1Q__",
    more_info: {
      song_count: "46",
      firstname: "JioSaavn",
      follower_count: "1922",
      last_updated: "1702344099",
      uid: "phulki_user",
    },
    explicit_content: "0",
    mini_obj: true,
  },
];
